import { CascaderProps, CascaderOption } from './index';
import { DataSet } from '../utils/getTreeDataFormatted';
export type OptionProps = {
    dense: boolean;
    parentId: CascaderOption["id"];
    showCheck: boolean;
    selected: Array<CascaderOption["id"]>;
    multiple: CascaderProps["multiple"];
    loadData: CascaderProps["loadData"];
    openChildren: (id: CascaderOption["id"], depth: number) => void;
    dataSet: DataSet<CascaderOption>;
    checkWithRelation: boolean;
    toggleCheck: (node: CascaderOption, checked: boolean) => void;
    searchData: CascaderOption[];
    onSelect: (o: CascaderOption) => void;
    startLoadData: (node: CascaderOption, depth: number) => void;
    depth: number;
    loadingId: CascaderOption["id"];
};
declare const _default: ({ dense, parentId, showCheck, multiple, selected, loadData, openChildren, dataSet, checkWithRelation, toggleCheck, searchData, onSelect, startLoadData, depth, loadingId }: OptionProps) => any;
export default _default;
