import { TreeSelectProp, TreeSelectOption } from './index';
import { DataSet } from '../utils/getTreeDataFormatted';
export type OptionsProps = {
    dense: boolean;
    showCheck: boolean;
    selected: Array<TreeSelectOption["id"]>;
    multiple: TreeSelectProp["multiple"];
    loadData: TreeSelectProp["loadData"];
    expandKeys: Array<TreeSelectOption["id"]>;
    toggleExpand: (id: TreeSelectOption["id"]) => void;
    dataSet: DataSet<TreeSelectOption>;
    checkWithRelation: boolean;
    loadingId: TreeSelectOption["id"];
    startLoadData: (node: TreeSelectOption) => void;
    searchData: TreeSelectOption[];
    onSelect: (o: TreeSelectOption) => void;
    toggleCheck: (node: TreeSelectOption, checked: boolean) => void;
};
declare const _default: ({ dense, showCheck, multiple, selected, loadData, expandKeys, toggleExpand, dataSet, checkWithRelation, loadingId, startLoadData, searchData, onSelect, toggleCheck, }: OptionsProps) => import("react/jsx-runtime").JSX.Element;
export default _default;
